### ISSUE TITLE
uhhhh

### ISSUE THREAD

**Issue by gabor-mkrsz** [bblanchon/disable-windows-keys#3]
"You can get this app for free by compiling it from the source code" yeah, that'd be simple, if I knew how.

**Comment by bblanchon** [comment]
Hi @gaboryt,

Like any cmake project:

```
cmake .
cmake --build .
```

Of course, you need to install CMake and Visual Studio.

Oh... and there is [a continuous build](https://github.com/bblanchon/disable-windows-keys/actions) 😉.

Best regards,
Benoit
