### ISSUE TITLE
wont build on windows 11

### ISSUE THREAD

**Issue by valueerrorx** [bblanchon/disable-windows-keys#5]
hi there.. thank you for this nifty little application
unfortunately i'm not able to build it on windows 11 dev build

do you have any suggestions ?
thx in advance

**Comment by bblanchon** [comment]
Hi @valueerrorx,

Can you provide more information?
What kind of error do you get?

Best regards,
Benoit

**Comment by valueerrorx** [comment]
thx for the quick reply...
first of all - i'm a total greenhorn when it comes to windows development (opened mvsc for the first time).. so the problem is most likely 70cm infront of the screen .. sorry.

./build.bat exits with "could not find any instance of visualstudio"  generater is visual studio 16 2019 (vs 2022 is installed)
if i just run cmake . it complains about missing nmake :-)

so i load the project as existing project in MSVC 2022 (as console application) 
- it first complains about win32
- then it says the platform toolset v143 can not be found.

so i activate "c++ desktop development" in tools, set the c-lang standard to default (legacy msvc), set the build folder
=> it finally builds.. but there is no exe file in the build folder... i've built an empty project.. lol

so i switched to folder view in solutions explorer (now i see all files) aaaaand voila...  there it is !! 
just not in the given build folder because there is another one defined in the cmake settings ..   what an odyssee for a simple node.js dev ;-)

i changed the keycodes in hook.c and can finally block "alt-tab" and other things
thank you for you time!

**Comment by bblanchon** [comment]
You're welcome @valueerrorx, I'm glad you managed to make it work.
