### ISSUE TITLE
Purchased this app thinking that it will disalbe Alt+ Shift shortcut while gaming

### ISSUE THREAD

**Issue by Jaksonas** [bblanchon/disable-windows-keys#6]
Hello,

Basically, the title. When I started playing, I immediately realised that your program only disables Win key shortcuts, so it is of no help to me.

Maybe you got any tips how to disable Alt+ Shift while in-game ONLY? Would love an automatic solution, if that is possible. I have no knowledge of programming, so I am not really able to compile/ write something myself.

Thanks.

**Comment by bblanchon** [comment]
Hi @Jaksonas,

The app's name is "Disable Windows Keys", not "Disable any key".
I don't plan on adding the ability to disable the Alt + Shift key combo, sorry.
I'll send you a refund.

Best regards,
Benoit
